# escape
ESCAPE_FAILED = 0
ESCAPE_NORMALIZED = 1
ESCAPE_ABSOLUTE = 2

# CUT_OPTION
WITHIN_CUT = 2
LEFT_CUT = 0
RIGHT_CUT = 1

# feature type
CATEGORICAL = 1
NUMERIC = 0

# for user_defined_subgroup.py
USER_CONTINUE_REFINE = 0
USER_NEXT_SUBGROUP = 1

# for mode
CLASSIFICATION = 0
SUBDISCOVERY = 1